### ISSUE TITLE
Issue running the adapter : Http Error:  404 Client Error: Not Found 

### ISSUE THREAD

**Issue by achrafcei** [microsoft/dbt-fabricspark#25]
Hello,
On a new project, I'm testing if I can use this adapter for my workloads, but when I try to just debug the project, I hit a snag : 

`Traceback (most recent call last):
  File "/home/unix/dbt/bin/dbt", line 8, in <module>
    sys.exit(cli())
  File "/home/unix/dbt/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/unix/dbt/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/unix/dbt/lib/python3.10/site-packages/click/core.py", line 1687, in invoke
    with sub_ctx:
  File "/home/unix/dbt/lib/python3.10/site-packages/click/core.py", line 466, in __exit__
    self.close()
  File "/home/unix/dbt/lib/python3.10/site-packages/click/core.py", line 595, in close
    self._exit_stack.close()
  File "/usr/lib/python3.10/contextlib.py", line 584, in close
    self.__exit__(None, None, None)
  File "/usr/lib/python3.10/contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/tracking.py", line 493, in track_run
    yield
  File "/usr/lib/python3.10/contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/factory.py", line 237, in adapter_management
    cleanup_connections()
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/factory.py", line 196, in cleanup_connections
    FACTORY.cleanup_connections()
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/factory.py", line 124, in cleanup_connections
    adapter.cleanup_connections()
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/base/impl.py", line 261, in cleanup_connections
    self.connections.cleanup_all()
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/fabricspark/connections.py", line 203, in cleanup_all
    livySession.disconnect()
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/fabricspark/livysession.py", line 489, in disconnect
    if __class__.livy_global_session.is_valid_session():
  File "/home/unix/dbt/lib/python3.10/site-packages/dbt/adapters/fabricspark/livysession.py", line 195, in is_valid_session
    self.connect_url + "/sessions/" + self.session_id,
TypeError: can only concatenate str (not "NoneType") to str`

It seems not to be able to start a session, is the api available to be used ?

**Comment by jcvdodson** [comment]
Have you applied for the Livy Public Preview? If your workspace/lakehouse hasn't been approved for Livy's Public Preview, then the adapter won't be able to connect.

**Comment by achrafcei** [comment]
Is there a link to apply for the public preview?

**Comment by dandical** [comment]
@jcvdodson I am getting this same issue, is this because livy needs to be explicitly turned on? If so how can we go about obtaining access to the livy preview?

**Comment by sudo-pradip** [comment]
Find any solution ?

**Comment by simaopedrotoga** [comment]
I'm too unable to establish a connection to Livy endpoint with error 404 by using the dbt-fabric adapter.
Is there a solution for this?
